[package]
name = "indexed_merkle_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-hash = "0.3.4"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.79"
redis = "0.22.1"
actix-web = "4"
actix-cors = "0.6.4"
async-redis-session = "0.2.2"
ed25519-dalek = "1.0.1"
ed25519 = "2.1.0"
base64 = "0.21.0"
tokio = { version = "1.16.1", features = ["full"] }
reqwest = "0.11.14"
ctrlc = "3.1.5"
num = "0.4.0"
bellman = "0.14.0"
pairing = "0.23.0"
bls12_381 = "0.8.0"
rand = "0.7.0"
hex = "0.4.3"
ff = "0.13.0"
openssl = "0.10"
